{
 "title": "Garden",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Ventilation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TemperatureSensor",
     "query": "SELECT mean(\"value\") FROM \"TemperatureSensor\" WHERE $timeFilter GROUP BY time($__interval), \"sensor_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TemperatureSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HumiditySensor",
     "query": "SELECT mean(\"value\") FROM \"HumiditySensor\" WHERE $timeFilter GROUP BY time($__interval), \"sensor_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HumiditySensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ventilation Actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "SELECT \"time\", \"state\" FROM \"actuator_events\" WHERE \"gpio_pin\" = '13' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Ventilation Actuator Last Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"time\", \"state\" FROM \"actuator_events\" WHERE \"gpio_pin\" = '13' AND $timeFilter"
    }
   ]
  },
  { "title": "Lighting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Light Intensity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LightSensor",
     "query": "SELECT mean(\"value\") FROM \"LightSensor\" WHERE $timeFilter GROUP BY time($__interval), \"sensor_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Light Intensity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LightSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lighting Actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "SELECT \"time\", \"state\" FROM \"actuator_events\" WHERE \"gpio_pin\" = '19' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Lighting Actuator Last Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"time\", \"state\" FROM \"actuator_events\" WHERE \"gpio_pin\" = '19' AND $timeFilter"
    }
   ]
  },
  { "title": "Irrigation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Soil Moisture",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SoilMoistureSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Soil Moisture",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SoilMoistureSensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pump Actuator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "SELECT \"time\", \"state\" FROM \"actuator_events\" WHERE \"gpio_pin\" = '26' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Pump Actuator Last Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"time\", \"state\" FROM \"actuator_events\" WHERE \"gpio_pin\" = '26' AND $timeFilter"
    }
   ]
  }
 ]
}